name: ORT-scan-test

on:
  push:
  workflow_dispatch:

jobs:
  ort:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/tsteenbe/node-docker:latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v5
      - name: Run Forgejo Action for ORT
        uses: tsteenbe/ort-ci-forgejo-action@main
