name: byocar-sample-app

on: 
  workflow_dispatch:

jobs:
  ort_scan:
    runs-on: ubuntu-latest
    name: Run ORT
    steps:
      - name: Use HTTPS instead of SSH for Git cloning
        run: git config --global url.https://github.com/.insteadOf ssh://git@github.com/
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          repository: tsteenbe/BYOCAR-sample-app
          ref: 63c3ec302a6775ed782a4582bc9671638d1782f2
      - name: Run GitHub action for ORT
        uses: tsteenbe/ort-ci-github-action@rc
        with:
          sw-name: 'BRING-YOUR-OWN-CAR (BYOCAR) Sample App'
          sw-version: '1.0.0'
          db-url: ${{ secrets.POSTGRES_URL }}
          db-username: ${{ secrets.POSTGRES_USERNAME }}
          db-password: ${{ secrets.POSTGRES_PASSWORD }}
          allow-dynamic-versions: 'true'
          ort-cli-analyze-args: '-l project=oss-project'
