name: ORT dev tsteenbe

on: 
  workflow_dispatch:

jobs:
  ort_scan:
    runs-on: ubuntu-latest
    name: Run ORT
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          repository: 'tsteenbe/mime-types' # 'finos/perspective'
      - name: Add SSH key
        run: |
          mkdir -p $HOME/.ssh
          echo "${{ secrets.SSH_KEY }}" > $HOME/.ssh/id_github
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > $HOME/.ssh/id_github.pub
          chmod 600 $HOME/.ssh/id_github*
          cat >>~/.ssh/config <<END
          Host github.com
            HostName ssh.github.com
            User git
            Port 443
            IdentityFile ~/.ssh/id_github
            StrictHostKeyChecking no
          END
      # - name: Prefer SSH over HTTPS for Git
      #   run: |
      #     git config --global url.ssh://git@github.com/.insteadOf https://github.com/
      - name: Run GitHub action for ORT
        uses: tsteenbe/ort-ci-github-action@main
        with:
          sw-name: 'Mime Types'
          sw-version: '2.1.35'
          db-url: ${{ secrets.POSTGRES_URL }}
          db-username: ${{ secrets.POSTGRES_USERNAME }}
          db-password: ${{ secrets.POSTGRES_PASSWORD }}
